import Head from "next/head";

import Banner from "../components/banner/Banner";
import Navbar from "../components/Navbar/Navbar";

import styles from "../styles/Home.module.css";
import SectionCards from "../components/SectionCards/SectionCards";

import {
    getNetflixOriginals,
    getTopRated,
    getTrending,
    getVideos,
    getWatchItAgainVideos,
} from "../lib/videos";
import requests from "../lib/requests";
import { verifyToken } from "../lib/utils";

export async function getServerSideProps(context) {
    const token = context.req ? context.req?.cookies.token : null;
    const userId = await verifyToken(token);
    if (!userId) {
        return {
            props: {},
            redirect: {
                destination: "/login",
                permanent: false,
            },
        };
    }
    const watchItAgainVideos = await getWatchItAgainVideos(userId, token);

    const trending = await getTrending();
    const netflixOriginals = await getNetflixOriginals();
    const topRated = await getTopRated();
    const actionMovies = await getVideos(requests.fetchActionMovies);
    const comedyMovies = await getVideos(requests.fetchComedyMovies);
    const horrorMovies = await getVideos(requests.fetchHorrorMovies);
    const romanceMovies = await getVideos(requests.fetchRomanceMovies);
    const documentariesMovies = await getVideos(requests.fetchDocumentaries);

    return {
        props: {
            watchItAgainVideos,
            trending: JSON.parse(JSON.stringify(trending)),
            netflixOriginals: JSON.parse(JSON.stringify(netflixOriginals)),
            topRated: JSON.parse(JSON.stringify(topRated)),
            actionMovies: JSON.parse(JSON.stringify(actionMovies)),
            comedyMovies: JSON.parse(JSON.stringify(comedyMovies)),
            horrorMovies: JSON.parse(JSON.stringify(horrorMovies)),
            romanceMovies: JSON.parse(JSON.stringify(romanceMovies)),
            documentariesMovies: JSON.parse(
                JSON.stringify(documentariesMovies)
            ),
        },
    };
}

export default function Home({
    watchItAgainVideos,
    trending,
    netflixOriginals,
    topRated,
    actionMovies,
    comedyMovies,
    horrorMovies,
    romanceMovies,
    documentariesMovies,
}) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Nextflix</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.main}>
                <Navbar />

                <Banner
                    title="Shrek"
                    subTitle="big green ogre AUUUGHH"
                    imgUrl="/static/shrek.jpg"
                />

                <div className={styles.sectionWrapper}>
                    <SectionCards
                        title="Watch it again"
                        videos={watchItAgainVideos}
                        size="large"
                    />
                    <SectionCards
                        title="Netflix Originals"
                        videos={netflixOriginals}
                        size="large"
                    />
                    <SectionCards
                        title="Trending"
                        videos={trending}
                        size="medium"
                    />
                    <SectionCards
                        title="Top Rated"
                        videos={topRated}
                        size="medium"
                    />
                    <SectionCards
                        title="Action"
                        videos={actionMovies}
                        size="small"
                    />
                    <SectionCards
                        title="Comedy"
                        videos={comedyMovies}
                        size="small"
                    />
                    <SectionCards
                        title="Horror"
                        videos={horrorMovies}
                        size="small"
                    />
                    <SectionCards
                        title="Romance"
                        videos={romanceMovies}
                        size="small"
                    />
                    <SectionCards
                        title="Documentaries"
                        videos={documentariesMovies}
                        size="small"
                    />
                </div>
            </div>
        </div>
    );
}
