import Head from 'next/head';

import Banner from '../components/banner/Banner';
import Navbar from '../components/Navbar/Navbar';

import styles from '../styles/Home.module.css';
import SectionCards from '../components/SectionCards/SectionCards';

import { getVideos } from '../lib/videos';

export async function getServerSideProps() {
    const videos = await getVideos();

    return {
        props: {
            videos,
        },
    };
}

export default function Home({ videos }) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Nextflix</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar username="joe@mama.com" />

            <Banner
                title="Shrek"
                subTitle="big green ogre AUUUGHH"
                imgUrl="/static/shrek.jpg"
            />

            <div className={styles.sectionWrapper}>
                <SectionCards title="Disney" videos={videos} size="large" />
                <SectionCards
                    title="Productivity"
                    videos={videos}
                    size="medium"
                />
            </div>
        </div>
    );
}
